# -*- coding: utf-8 -*-
"""Conversion_Causal_Factors.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1z14JD0yZ7JDkwVzssf7Cg8nRFRfv4W1S
"""

import pandas as pd
import streamlit as st

st.title("Causal Factor Impact Calculator")

st.write("""
This tool calculates the impact of causal factors on conversion.
Impact = sensitivity × metric change.

Includes your key e-commerce drivers:
- Delivery Estimate Variance
- Payment Successful Rate %
- Source Mix
- Search CTR
- Discount Change
- Price Competitiveness
- Product Availability

It also highlights the **Top 10 causal factors** by absolute impact.
""")

# --------------------------------------------------------------------
# Default causal factors you requested
# --------------------------------------------------------------------
default_data = pd.DataFrame({
    "factor": [
        "Delivery Estimate Variance",
        "Payment Successful Rate %",
        "Source Mix Change",
        "Search CTR Change",
        "Discount Change %",
        "Price Competitiveness Index Change",
        "Product Availability % Change"
    ],

    # Placeholder sensitivities (editable by user)
    "sensitivity_pp_per_unit": [
        -0.3,   # PP impact per +1 day added to delivery estimate
        0.4,    # PP impact per +1% improvement in payment success rate
        0.2,    # PP impact per +1% source-mix shift to high-intent channels
        0.15,   # PP impact per +1% CTR increase
        0.5,    # PP impact per +1% more discount
        -0.25,  # PP per +1% price increase vs competitors
        0.35    # PP per +1% improvement in availability
    ],

    # Placeholder metric changes (editable by user)
    "metric_change_units": [
        1,      # delivery got 1 day slower
        -2,     # payment success dropped by 2%
        3,      # 3% shift in source mix toward high-intent
        1,      # 1% increase in search CTR
        5,      # discount increased 5%
        2,      # price competitiveness worsened by 2%
        -4      # availability dropped by 4%
    ]
})

# Editable table for causal factors
st.subheader("Causal Factors Input")
df = st.data_editor(
    default_data,
    key="factors_table",
    num_rows="dynamic",
    width='stretch'
)

# --------------------------------------------------------------------
# Impact calculation
# --------------------------------------------------------------------
df["impact_pp"] = df["sensitivity_pp_per_unit"] * df["metric_change_units"]
df["abs_impact_pp"] = df["impact_pp"].abs()

st.subheader("Impact Results")
st.dataframe(df.drop(columns=["abs_impact_pp"]))

# Total conversion impact
total_impact = df["impact_pp"].sum()

st.metric(
    label="Total Conversion Impact (percentage points)",
    value=f"{total_impact:.2f} PP",
    delta=f"{total_impact:.2f} PP"
)

# --------------------------------------------------------------------
# Top 10 causal factors
# --------------------------------------------------------------------
st.subheader("Top 10 Causal Factors by Absolute Impact")

top10 = df.sort_values("abs_impact_pp", ascending=False).head(10)
st.dataframe(top10[["factor", "impact_pp"]])

st.write("""
### Interpretation
- Ranking uses absolute impact (strongest drivers first).
- Positive impact = conversion lift
- Negative impact = conversion decline
""")





