# -*- coding: utf-8 -*-
"""streamlit_app

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nTsOtwBNrN7yw0pDzG1ZV-A0naPGLZps
"""

import streamlit as st
import pandas as pd
import numpy as np
import random

st.set_page_config(layout="wide", page_title="Product Module Simulation")

# -------------------------------------------------------------------------
# Category-specific Optimal Weight Profiles
# -------------------------------------------------------------------------
CATEGORY_WEIGHTS = {
    "Collectibles":     {"relevance":0.35, "diversity":0.30, "freshness":0.20, "monetization":0.15},
    "Electronics":      {"relevance":0.45, "diversity":0.15, "freshness":0.10, "monetization":0.30},
    "Toys":             {"relevance":0.30, "diversity":0.25, "freshness":0.30, "monetization":0.15},
    "Makeup / Beauty":  {"relevance":0.40, "diversity":0.20, "freshness":0.25, "monetization":0.15}
}

# -------------------------------------------------------------------------
# Mock Data Generator
# -------------------------------------------------------------------------
def generate_mock_products(n, category):
    names = {
        "Collectibles": [
            "Pokemon Booster Pack", "Vintage Comic Book", "Signed Baseball", 
            "Funkopop Exclusive", "Retro Trading Card"
        ],
        "Electronics": [
            "Apple AirPods Pro", "Samsung Galaxy Watch", "Sony WH1000XM5 Headphones",
            "Lenovo ThinkPad X1", "iPad Mini"
        ],
        "Toys": [
            "Lego Star Wars Set", "Barbie Dream House", "Hot Wheels Track Builder",
            "Nerf Elite Blaster", "Pokemon Plush"
        ],
        "Makeup / Beauty": [
            "Fenty Gloss Bomb", "Charlotte Tilbury Pillow Talk Trio", 
            "Rare Beauty Lip Oil", "Dior Lip Glow", "Huda Beauty Palette"
        ]
    }

    price_bands = ["Low", "Mid", "High"]

    data = []
    for i in range(n):
        data.append({
            "item_id": f"ITEM_{i+1}",
            "name": random.choice(names[category]),
            "relevance_score": random.uniform(0.4, 1.0),
            "recommendation_score": random.uniform(0.4, 1.0),
            "quality_score": random.uniform(0.4, 1.0),
            "popularity_score": random.uniform(0.4, 1.0),
            "seller_health": random.uniform(0.4, 1.0),
            "freshness_score": random.uniform(0.3, 1.0),
            "sponsored": random.choice([0,0,0,1]),  # 25% sponsored
            "subcat": random.choice(["Premium", "Budget", "Collector", "Classic", "Trending"]),
            "price_band": random.choice(price_bands)
        })
    return pd.DataFrame(data)

# -------------------------------------------------------------------------
# Scoring Function
# -------------------------------------------------------------------------
def compute_score(row, used_subcats, weights, current_sponsored, max_sponsored):
    score = (
        row["relevance_score"]      * weights["relevance"] +
        row["freshness_score"]      * weights["freshness"] +
        row["popularity_score"]     * 0.10 +
        row["quality_score"]        * 0.10 +
        row["seller_health"]        * 0.10
    )

    # Diversity penalty
    if row["subcat"] in used_subcats:
        score -= weights["diversity"] * used_subcats[row["subcat"]]

    # Sponsored bonus
    if row["sponsored"] == 1 and current_sponsored < max_sponsored:
        score += weights["monetization"]

    return score

# -------------------------------------------------------------------------
# Simulation Loop (6 Slots)
# -------------------------------------------------------------------------
def simulate_selection(df, weights, max_sponsored=2):
    df = df.copy()
    selected = []
    used_subcats = {}
    current_sponsored = 0

    for _ in range(6):
        df["dynamic_score"] = df.apply(
            lambda row: compute_score(
                row, 
                used_subcats, 
                weights,
                current_sponsored, 
                max_sponsored
            ), 
            axis=1
        )

        best_item = df.sort_values("dynamic_score", ascending=False).iloc[0]
        selected.append(best_item)

        subcat = best_item["subcat"]
        used_subcats[subcat] = used_subcats.get(subcat, 0) + 1
        if best_item["sponsored"] == 1:
            current_sponsored += 1

        df = df[df["item_id"] != best_item["item_id"]]

    return selected

# -------------------------------------------------------------------------
# UI
# -------------------------------------------------------------------------
st.title("🛒 E-Commerce 6-Slot Horizontal Module Simulation")

category = st.sidebar.selectbox(
    "Choose Category",
    ["Collectibles", "Electronics", "Toys", "Makeup / Beauty"]
)

st.sidebar.write("### Optimal Embedded Weights")
optimal = CATEGORY_WEIGHTS[category]
st.sidebar.write(optimal)

num_products = st.sidebar.number_input("Number of Products", 10, 100, 40)
max_sponsored = st.sidebar.slider("Max Sponsored Slots", 0, 6, 2)

df = generate_mock_products(num_products, category)

if st.sidebar.button("Run Simulation"):
    selected = simulate_selection(df, optimal, max_sponsored)

    st.subheader("🎯 Final 6 Recommended Items")
    cols = st.columns(6)

    for i, item in enumerate(selected):
        with cols[i]:
            st.markdown(f"### Slot {i+1}")
            st.write(f"**{item['name']}**")
            st.write(f"Subcat: {item['subcat']}")
            st.write(f"Sponsored: {'Yes' if item['sponsored'] else 'No'}")
            st.write(f"Freshness: {item['freshness_score']:.2f}")
            st.write(f"Relevance: {item['relevance_score']:.2f}")
            st.write(f"DScore: {item['dynamic_score']:.3f}")

    st.subheader("📦 Full Catalog Pool")
    st.dataframe(df)
else:
    st.info("Choose a category and click Run Simulation.")
