# -*- coding: utf-8 -*-
"""streamlit_app

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nTsOtwBNrN7yw0pDzG1ZV-A0naPGLZps
"""

import streamlit as st
import pandas as pd
import numpy as np

st.title("E-commerce Item Selection Simulation")
st.subheader("All categories compete for the 6-slot product module")

# -----------------------------
# Category optimal weights
# (intuition-building)
# -----------------------------
category_weights = {
    "Collectibles":  {"relevance": 0.55, "diversity": 0.30, "freshness": 0.40, "monetization": 0.25},
    "Electronics":   {"relevance": 0.75, "diversity": 0.10, "freshness": 0.35, "monetization": 0.40},
    "Toys":          {"relevance": 0.60, "diversity": 0.25, "freshness": 0.45, "monetization": 0.20},
    "Makeup":        {"relevance": 0.65, "diversity": 0.20, "freshness": 0.50, "monetization": 0.30},
}

# Display optimal values
with st.expander("Optimal Values per Category (intuition)"):
    st.write(pd.DataFrame(category_weights).T)

# -----------------------------
# Create sample item inventory
# -----------------------------
np.random.seed(42)

items = []
categories = list(category_weights.keys())

for cat in categories:
    for i in range(10):
        items.append({
            "item_id": f"{cat[:3]}_{i}",
            "category": cat,
            "relevance": np.random.uniform(0.4, 0.95),
            "diversity_signal": np.random.uniform(0.1, 0.9),
            "freshness": np.random.uniform(0.2, 0.95),
            "monetization": np.random.uniform(0.1, 0.95),
        })

df = pd.DataFrame(items)

st.subheader("Global Weight Controls (applied to final scoring)")
rel = st.slider("Relevance Weight", 0.0, 1.0, 0.5)
div = st.slider("Diversity Weight", 0.0, 1.0, 0.2)
fre = st.slider("Freshness Weight", 0.0, 1.0, 0.3)
mon = st.slider("Monetization Weight", 0.0, 1.0, 0.3)

# -----------------------------------
# Compute final global score
# -----------------------------------
def score(row):
    cat = row["category"]
    catw = category_weights[cat]
    
    # Combine item signals with category-specific intuition
    return (
        row["relevance"]     * rel * catw["relevance"] +
        row["diversity_signal"] * div * catw["diversity"] +
        row["freshness"]     * fre * catw["freshness"] +
        row["monetization"]  * mon * catw["monetization"]
    )

df["final_score"] = df.apply(score, axis=1)

# Pick top 6 competing items
top6 = df.sort_values("final_score", ascending=False).head(6)

st.subheader("Selected Items (Top 6 Ranked Across All Categories)")
st.write(top6[["item_id", "category", "final_score"]])
