# -*- coding: utf-8 -*-
"""streamlit_app

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nTsOtwBNrN7yw0pDzG1ZV-A0naPGLZps
"""

# -*- coding: utf-8 -*-
"""streamlit_app - simple table output"""

import streamlit as st
import pandas as pd
import numpy as np
import random
from collections import Counter

st.set_page_config(layout="wide", page_title="6-Slot Module Simulation — Category-aware")

# -------------------------
# Embedded optimal weights per category
CATEGORY_WEIGHTS = {
    "Collectibles": {"relevance": 0.55, "diversity": 0.30, "freshness": 0.40, "monetization": 0.25},
    "Electronics":  {"relevance": 0.75, "diversity": 0.10, "freshness": 0.35, "monetization": 0.40},
    "Toys":         {"relevance": 0.60, "diversity": 0.25, "freshness": 0.45, "monetization": 0.20},
    "Makeup":       {"relevance": 0.65, "diversity": 0.20, "freshness": 0.50, "monetization": 0.30},
    "Grocery":      {"relevance": 0.70, "diversity": 0.15, "freshness": 0.70, "monetization": 0.35},
    "Motorcycle":   {"relevance": 0.80, "diversity": 0.05, "freshness": 0.30, "monetization": 0.50},
    "Cars":         {"relevance": 0.85, "diversity": 0.05, "freshness": 0.25, "monetization": 0.60},
}
ALL_CATEGORIES = list(CATEGORY_WEIGHTS.keys())

# -------------------------
# Generate mock product pool
@st.cache_data
def generate_products(n=80, seed=42):
    random.seed(seed)
    np.random.seed(seed)
    products = []
    price_bands = ["Low", "Mid", "High"]

    for i in range(n):
        cat = random.choice(ALL_CATEGORIES)
        products.append({
            "item_id": f"{cat[:3].upper()}_{i+1}",
            "name": f"{cat} Item {i+1}",
            "category": cat,
            "relevance_score": np.clip(np.random.normal(0.6, 0.18), 0, 1),
            "recommendation_score": np.clip(np.random.normal(0.5, 0.2), 0, 1),
            "quality_score": np.clip(np.random.normal(0.6, 0.2), 0, 1),
            "popularity_score": np.clip(np.random.beta(2,5), 0, 1),
            "seller_health": np.clip(np.random.normal(0.75, 0.15), 0, 1),
            "freshness_score": np.clip(np.random.exponential(0.6), 0, 1),
            "sponsored": random.choices([0,1], weights=[0.8,0.2])[0],
            "price_band": random.choice(price_bands)
        })
    return pd.DataFrame(products)

# -------------------------
# Compute dynamic score
def compute_dynamic_score(row, global_weights, used_subcats, slot_idx, current_sponsored, max_sponsored, use_category_bias=True):
    base = (
        row["relevance_score"] * global_weights["relevance"] +
        row["recommendation_score"] * global_weights["personalization"] +
        row["quality_score"] * global_weights["quality"] +
        row["popularity_score"] * global_weights["popularity"] +
        row["seller_health"] * global_weights["seller_health"] +
        row["freshness_score"] * global_weights["freshness"]
    )

    if use_category_bias:
        cat_profile = CATEGORY_WEIGHTS.get(row["category"])
        if cat_profile:
            align = (
                row["relevance_score"] * cat_profile["relevance"] +
                row["freshness_score"] * cat_profile["freshness"] +
                row["popularity_score"] * (cat_profile["monetization"] * 0.8) +
                (1.0 - row["popularity_score"]) * (cat_profile["diversity"] * 0.6)
            )
            base = 0.85 * base + 0.15 * align

    if row["category"] in used_subcats:
        base -= 0.12 * used_subcats[row["category"]]

    if slot_idx == 4:
        base += 0.12 * row["freshness_score"]

    if row["sponsored"] == 1 and current_sponsored < max_sponsored:
        base += global_weights.get("sponsored_bonus", 0.12)

    return base

# -------------------------
# Simulate 6-slot module
def simulate_module(df_pool, global_weights, max_sponsored=2, use_category_bias=True):
    pool = df_pool.copy().reset_index(drop=True)
    selected = []
    used_subcats = {}
    current_sponsored = 0

    for slot in range(1,7):
        pool["dynamic_score"] = pool.apply(
            lambda r: compute_dynamic_score(r, global_weights, used_subcats, slot, current_sponsored, max_sponsored, use_category_bias),
            axis=1
        )
        best_idx = pool["dynamic_score"].idxmax()
        best_row = pool.loc[best_idx]
        selected.append(best_row)

        cat = best_row["category"]
        used_subcats[cat] = used_subcats.get(cat, 0) + 1
        if best_row["sponsored"] == 1:
            current_sponsored += 1

        pool = pool.drop(index=best_idx).reset_index(drop=True)

    return pd.DataFrame(selected).reset_index(drop=True)

# -------------------------
# Streamlit UI
st.title("6-Slot Module Simulation — Category-aware")

# Controls
num_items = st.number_input("Product pool size", 30, 500, 120, 10)
max_sponsored = st.slider("Max sponsored slots", 0, 6, 2)
seed = st.number_input("Random seed", 0, 9999, 42)
use_cat_bias = st.checkbox("Use category optimal bias", True)

st.subheader("Global weight sliders")
global_weights = {
    "relevance": st.slider("Relevance", 0.0, 1.0, 0.30),
    "personalization": st.slider("Personalization", 0.0, 1.0, 0.25),
    "quality": st.slider("Quality", 0.0, 1.0, 0.15),
    "popularity": st.slider("Popularity", 0.0, 1.0, 0.10),
    "seller_health": st.slider("Seller Health", 0.0, 1.0, 0.10),
    "freshness": st.slider("Freshness", 0.0, 1.0, 0.05),
    "sponsored_bonus": st.slider("Sponsored Bonus", 0.0, 0.5, 0.12)
}

if st.button("Run Simulation"):
    df_pool = generate_products(num_items, seed)
    selected_df = simulate_module(df_pool, global_weights, max_sponsored, use_cat_bias)

    st.subheader("Category optimal values (all categories)")
    st.dataframe(pd.DataFrame(CATEGORY_WEIGHTS).T)

    st.subheader("Selected 6-slot items")
    st.dataframe(selected_df[['item_id','name','category','sponsored','price_band','dynamic_score']])

    st.subheader("Full candidate pool (partial view)")
    st.dataframe(df_pool.sample(min(50,len(df_pool)), random_state=seed))
